In [1]:
import numpy

In [3]:
import numpy as np

In [18]:
arr = np.array([1,2,3,4,5])

In [23]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[5,7,3,2]])

In [24]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 7, 3, 2]])

In [22]:
arr.shape

(5,)

In [25]:
arr.size

5

In [26]:
arr.dtype

dtype('int32')

In [27]:
arr.ndim

1

In [28]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 7, 3, 2]])

In [29]:
arr_2d.size

12

In [30]:
arr_2d.dtype

dtype('int32')

In [31]:
arr_2d.ndim

2

In [32]:
arr_2d.shape

(3, 4)

In [53]:
a = np.arange(0,16).reshape(4,4)
b = np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
a*b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [56]:
np.add(a,b)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [57]:
np.subtract(a,b)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
np.multiply(a,b)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [59]:
np.dot(a,b)

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [68]:
r_arr = np.random.randint(1,50,24).reshape(4,6)
r_arr

array([[16, 12, 23, 31, 35, 36],
       [42, 33, 17, 36, 43, 37],
       [31, 27,  8, 23, 30, 26],
       [ 7, 41, 20, 44, 28,  3]])

In [77]:
for i in range(0,4):
    print(r_arr[i][2])

23
17
8
20


In [73]:
r_arr.size

24

In [79]:
r_arr

array([[16, 12, 23, 31, 35, 36],
       [42, 33, 17, 36, 43, 37],
       [31, 27,  8, 23, 30, 26],
       [ 7, 41, 20, 44, 28,  3]])

In [98]:
r_arr[:][2]

array([31, 27,  8, 23, 30, 26])